# JavaScript action
name: Upload to CodeDx
description: Uploads a result of Dependency Check to CodeDx

inputs:
  file:
    description: The file containing the dependencies to load
    required: true
  serverUrl:
    description: The URL of the CodeDx serverUrl
    required: true
  projectId:
    description: The ID of the CodeDx project
    required: true
  branchName:
    description: The name of the CodeDX project branch
    required: true
  key:
    description: The API Key to authenticate the CodeDx calls
    required: true

runs:
  using: "node16"
  main: "./dist/index.js"
