name: Dependencies
description: Install UI Kit dependencies

runs:
  using: "composite"
  steps:
    - name: Install Node.js
      uses: actions/setup-node@v4
      with:
        node-version: 18

    - name: Install dependencies
      # ensure dev dependencies are installed
      run: npm ci --include=dev
      shell: bash
