/* eslint sort-keys: error */
export default {
  "-- Components": {
    title: "Components",
    type: "separator",
  },
  index: "Get started",
  // eslint-disable-next-line sort-keys
  accordion: "Accordion",
  "action-bar": "Action Bar",
  "app-switcher": "App Switcher",
  avatar: "Avatar",
  "avatar-group": "Avatar Group",
  badge: "Badge",
  banner: "Banner",
  breadcrumb: "Breadcrumb",
  "bulk-actions": "Bulk Actions",
  button: "Button",
  card: "Card",
  carousel: "Carousel",
  checkbox: "Checkbox",
  "checkbox-group": "Checkbox Group",
  "code-editor": "Code Editor",
  "color-picker": "Color Picker",
  container: "Container",
  "date-picker": "Date Picker",
  dialog: "Dialog",
  "dot-pagination": "Dot Pagination",
  drawer: "Drawer",
  dropdown: "Dropdown",
  "dropdown-menu": "Dropdown Menu",
  "empty-state": "Empty State",
  "file-uploader": "File Uploader",
  "filter-group": "Filter Group",
  footer: "Footer",
  "form-element": "Form Element",
  "global-actions": "Global Actions",
  grid: "Grid",
  header: "Header",
  "icon-container": "Icon Container",
  input: "Input",
  "list-container": "List Container",
  loading: "Loading",
  "loading-container": "Loading Container",
  "multi-button": "Multi Button",
  "number-input": "Number Input",
  "overflow-tooltip": "Overflow Tooltip",
  pagination: "Pagination",
  panel: "Panel",
  "progress-bar": "Progress Bar",
  "query-builder": "Query Builder",
  radio: "Radio",
  "radio-group": "Radio Group",
  "scroll-to-horizontal": "ScrollTo Horizontal",
  "scroll-to-vertical": "ScrollTo Vertical",
  "search-input": "Search Input",
  section: "Section",
  select: "Select",
  "selection-list": "Selection List",
  "simple-grid": "Simple Grid",
  skeleton: "Skeleton",
  slider: "Slider",
  snackbar: "Snackbar",
  "snackbar-provider": "Snackbar Provider",
  stack: "Stack",
  switch: "Switch",
  table: "Table",
  tabs: "Tabs",
  tag: "Tag",
  "tags-input": "Tags Input",
  textarea: "Textarea",
  "time-picker": "Time Picker",
  "toggle-button": "Toggle Button",
  tooltip: "Tooltip",
  "tree-view": "Tree View",
  typography: "Typography",
  "vertical-navigation": "Vertical Navigation",
  // eslint-disable-next-line sort-keys
  "-- Lab": {
    title: "Lab",
    type: "separator",
  },
  lab: "Get started",
  // eslint-disable-next-line sort-keys
  blade: "Blade",
  blades: "Blades",
  dashboard: "Dashboard",
  "step-navigation": "Step Navigation",
  wizard: "Wizard",
  // eslint-disable-next-line sort-keys
  "-- Canvas": {
    title: "Canvas",
    type: "separator",
  },
  canvas: "Get Started",
  "canvas-bottom-panel": "Bottom Panel",
  "canvas-side-panel": "Side Panel",
  "canvas-toolbar": "Toolbar",
  "canvas-toolbar-tabs": "Toolbar Tabs",
};
