// latest versions
const ds5 = "5.9.5";
const pentahoPlus = "0.6.0";

export const alignmentData: Record<
  string,
  { ds5: string; pentahoPlus: string }
> = {
  Accordion: { ds5, pentahoPlus },
  ActionBar: { ds5, pentahoPlus },
  AppSwitcher: { ds5, pentahoPlus },
  Avatar: { ds5, pentahoPlus },
  AvatarGroup: { ds5, pentahoPlus },
  Badge: { ds5, pentahoPlus },
  Banner: { ds5, pentahoPlus },
  BreadCrumb: { ds5, pentahoPlus },
  BulkActions: { ds5, pentahoPlus },
  Button: { ds5, pentahoPlus },
  Card: { ds5, pentahoPlus },
  Carousel: { ds5, pentahoPlus },
  Checkbox: { ds5, pentahoPlus },
  CheckboxGroup: { ds5, pentahoPlus },
  CodeEditor: { ds5, pentahoPlus },
  ColorPicker: { ds5, pentahoPlus },
  Container: { ds5, pentahoPlus },
  DatePicker: { ds5, pentahoPlus },
  Dialog: { ds5, pentahoPlus },
  DotPagination: { ds5, pentahoPlus },
  Drawer: { ds5, pentahoPlus },
  Dropdown: { ds5, pentahoPlus },
  DropDownMenu: { ds5, pentahoPlus },
  EmptyState: { ds5, pentahoPlus },
  FileUploader: { ds5, pentahoPlus },
  FilterGroup: { ds5, pentahoPlus },
  Footer: { ds5, pentahoPlus },
  GlobalActions: { ds5, pentahoPlus },
  Header: { ds5, pentahoPlus },
  Input: { ds5, pentahoPlus },
  Loading: { ds5: "5.9.3", pentahoPlus },
  MultiButton: { ds5, pentahoPlus },
  NumberInput: { ds5, pentahoPlus },
  Pagination: { ds5, pentahoPlus },
  ProgressBar: { ds5: "5.9.3", pentahoPlus },
  Radio: { ds5, pentahoPlus },
  RadioGroup: { ds5, pentahoPlus },
  ScrollToHorizontal: { ds5, pentahoPlus },
  ScrollToVertical: { ds5, pentahoPlus },
  SearchInput: { ds5, pentahoPlus },
  Section: { ds5, pentahoPlus },
  Select: { ds5, pentahoPlus },
  Skeleton: { ds5, pentahoPlus },
  Slider: { ds5: "5.9.3", pentahoPlus },
  Snackbar: { ds5, pentahoPlus },
  Switch: { ds5, pentahoPlus },
  // Table: {  ds5, pentahoPlus },
  Tabs: { ds5, pentahoPlus },
  Tag: { ds5, pentahoPlus },
  TagsInput: { ds5, pentahoPlus },
  TextArea: { ds5, pentahoPlus },
  TimePicker: { ds5, pentahoPlus },
  ToggleButton: { ds5, pentahoPlus },
  Tooltip: { ds5, pentahoPlus },
  Typography: { ds5, pentahoPlus },
  VerticalNavigation: { ds5: "5.9.3", pentahoPlus },
};
