name: Artifacts
description: Build UI Kit Documentation and App

runs:
  using: "composite"
  steps:
    - name: Checkout
      uses: actions/checkout@v3

    - name: Install Dependencies
      uses: ./.github/actions/install-dependencies

    - name: Build Documentation
      run: npm run build:doc
      env:
        NODE_OPTIONS: "--max_old_space_size=8192"
      shell: bash

    - name: Archive Documentation
      uses: actions/upload-artifact@v3
      with:
        name: documentation
        path: ${{ github.workspace }}/dist
        retention-days: 2

    - name: Build App
      run: npm run build:app -- --base=${{ env.APP_BASE_PATH }}
      shell: bash

    - name: Archive App
      uses: actions/upload-artifact@v3
      with:
        name: app
        path: ${{ github.workspace }}/apps/app/dist
        retention-days: 2
