*** Setting ***
Resource          ../_keywords.resource


*** Variables ***
${dropdown}                       css:div[class*='HvBaseDropdown-root']
${dropdownHeader}                 css:div[id*=dropdown][id*=header]
${container}                      css:div[class*='HvBaseDropdown-panel']
${inputInContainer}               css:input[id*='input-dropdown']
${withContent}                    ${components}basedropdown--with-content
