// to transform commonjs to es6 (required by react-router-dom)
import fs from "fs";
import { createRequire } from "node:module";
import path from "path";
import commonjs from "@rollup/plugin-commonjs";
// for support json manipulation (used by the module to export)
import json from "@rollup/plugin-json";
// for resolve and include dependencies (node_modules)
import resolve from "@rollup/plugin-node-resolve";
// replace production mode
import replace from "@rollup/plugin-replace";
// minified version
import terser from "@rollup/plugin-terser";

const require = createRequire(import.meta.url);

const createEsmBundleConfig = (name, external, suffix = "production.min") => {
  const cleanName = name.replaceAll("/", "-").replace("@", "");

  const packageFolder = path.dirname(require.resolve(name + "/package.json"));
  const packageJson = JSON.parse(
    fs.readFileSync(path.join(packageFolder, "package.json"), "utf8"),
  );
  const version = packageJson.version;

  return {
    input: `src/export-externals/export-${cleanName}.js`,
    output: {
      format: "esm",
      file: `dist/esm-externals/${cleanName}.${suffix}.js`,
      sourcemap: true,
      banner: `/* @preserve ${name}@${version} esm bundle generated by Hitachi Vantara - Boba Fett team */`,
      exports: "named",
    },
    external,
    plugins: [
      commonjs(),
      resolve(),
      json(),
      replace({
        preventAssignment: true,
        values: {
          "process.env.NODE_ENV": '"production"',
        },
      }),
      terser(),
    ],
  };
};

export default [
  createEsmBundleConfig("react"),
  createEsmBundleConfig("react-dom", ["react"]),
  createEsmBundleConfig("react-router-dom", ["react"]),
  createEsmBundleConfig("@emotion/cache"),
  createEsmBundleConfig("@emotion/react", ["react", "@emotion/cache"]),
];
