name: Feature request 💄
description: Suggest a new idea for NEXT UI Kit.
labels: ['⌛ needs triage']
body:
  - type: markdown
    attributes:
      value: |
        Please provide a searchable summary of the issue in the title above ⬆️.

        Thanks for contributing by creating an issue! ❤️
  - type: checkboxes
    attributes:
      label: Latest version
      description: We roll bug fixes, performance enhancements, and other improvements into new releases.
      options:
        - label: I have tested the latest version
          required: true
  - type: checkboxes
    attributes:
      label: No Hitachi confidential content
      description: Keep in mind this is a public repository. Do not share any information that you might even think is Hitachi confidential. Logos, references to work in progress projects, and of course, credentials. We will delete the issue immediately. 
      options:
        - label: I'm not including any Hitachi confidential content
          required: true                
  - type: textarea
    attributes:
      label: Summary 💡
      description: Describe how it should work.
  - type: textarea
    attributes:
      label: Examples 🌈
      description: Provide a link to the NEXT Design System specification, other implementations, or screenshots of the expected behavior.
  - type: textarea
    attributes:
      label: Motivation 🔦
      description: What are you trying to accomplish? How has the lack of this feature affected you? Providing context helps us come up with a solution that is more useful in the real world.