import { HvTreemapData } from "../../types/generic";

export const data: HvTreemapData[] = [
  {
    value: [1226629000],
    name: "Health and Human Services",
    id: "branch-8",
    discretion: null,
    children: [
      {
        value: [1105220000],
        name: "Centers for Medicare and Medicaid Services",
        id: "leaf-135",
        discretion: "mandatory",
      },
      {
        value: [34502000],
        name: "Administration for Children and Families",
        id: "leaf-131",
        discretion: "mandatory",
      },
      {
        value: [31829000],
        name: "National Institutes of Health",
        id: "leaf-127",
        discretion: "discretionary",
      },
      {
        value: [16180000],
        name: "Administration for Children and Families",
        id: "leaf-118",
        discretion: "discretionary",
      },
      {
        value: [7324000],
        name: "Centers for Medicare and Medicaid Services",
        id: "leaf-121",
        discretion: "discretionary",
      },
      {
        value: [6821000],
        name: "Health Resources and Services Administration",
        id: "leaf-125",
        discretion: "discretionary",
      },
      {
        value: [5893000],
        name: "Centers for Disease Control and Prevention",
        id: "leaf-120",
        discretion: "discretionary",
      },
      {
        value: [4624000],
        name: "Indian Health Services",
        id: "leaf-126",
        discretion: "discretionary",
      },
      {
        value: [3387000],
        name: "Substance Abuse and Mental Health Services Administration",
        id: "leaf-130",
        discretion: "discretionary",
      },
      {
        value: [2744000],
        name: "Food and Drug Administration",
        id: "leaf-124",
        discretion: "discretionary",
      },
      {
        value: [2237000],
        name: "Administration on Aging",
        id: "leaf-119",
        discretion: "discretionary",
      },
      {
        value: [2155000],
        name: "Health Resources and Services Administration",
        id: "leaf-139",
        discretion: "mandatory",
      },
      {
        value: [1063000],
        name: "Departmental Management",
        id: "leaf-123",
        discretion: "discretionary",
      },
      {
        value: [809000],
        name: "Centers for Disease Control and Prevention",
        id: "leaf-134",
        discretion: "mandatory",
      },
      {
        value: [647000],
        name: "Program Support Center",
        id: "leaf-143",
        discretion: "mandatory",
      },
      {
        value: [473000],
        name: "Departmental Management",
        id: "leaf-137",
        discretion: "mandatory",
      },
      {
        value: [210000],
        name: "Administration on Aging",
        id: "leaf-132",
        discretion: "mandatory",
      },
      {
        value: [166000],
        name: "National Institutes of Health",
        id: "leaf-141",
        discretion: "mandatory",
      },
      {
        value: [158000],
        name: "Indian Health Services",
        id: "leaf-140",
        discretion: "mandatory",
      },
      {
        value: [93000],
        name: "Substance Abuse and Mental Health Services Administration",
        id: "leaf-144",
        discretion: "mandatory",
      },
      {
        value: [53000],
        name: "Office of the Inspector General",
        id: "leaf-128",
        discretion: "discretionary",
      },
      {
        value: [39000],
        name: "Program Support Center",
        id: "leaf-129",
        discretion: "discretionary",
      },
      {
        value: [2000],
        name: "Food and Drug Administration",
        id: "leaf-138",
        discretion: "mandatory",
      },
    ],
  },
  {
    value: [818284000],
    name: "Social Security Administration",
    id: "branch-34",
    discretion: null,
    children: [
      {
        value: [808041000],
        name: "Social Security Administration",
        id: "leaf-531",
        discretion: "mandatory",
      },
      {
        value: [10243000],
        name: "Social Security Administration",
        id: "leaf-530",
        discretion: "discretionary",
      },
    ],
  },
  {
    value: [677483000],
    name: "Defense--Military Programs",
    id: "branch-5",
    discretion: null,
    children: [
      {
        value: [294891000],
        name: "Operation and Maintenance",
        id: "leaf-77",
        discretion: "discretionary",
      },
      {
        value: [154057000],
        name: "Military Personnel",
        id: "leaf-76",
        discretion: "discretionary",
      },
      {
        value: [128051000],
        name: "Procurement",
        id: "leaf-78",
        discretion: "discretionary",
      },
      {
        value: [75722000],
        name: "Research, Development, Test, and Evaluation",
        id: "leaf-79",
        discretion: "discretionary",
      },
      {
        value: [13073000],
        name: "Military Construction",
        id: "leaf-75",
        discretion: "discretionary",
      },
      {
        value: [5475000],
        name: "Military Personnel",
        id: "leaf-83",
        discretion: "mandatory",
      },
      {
        value: [3136000],
        name: "Revolving and Management Funds",
        id: "leaf-80",
        discretion: "discretionary",
      },
      {
        value: [1695000],
        name: "Family Housing",
        id: "leaf-74",
        discretion: "discretionary",
      },
      {
        value: [836000],
        name: "Operation and Maintenance",
        id: "leaf-84",
        discretion: "mandatory",
      },
      {
        value: [447000],
        name: "Trust Funds",
        id: "leaf-88",
        discretion: "mandatory",
      },
      {
        value: [100000],
        name: "Research, Development, Test, and Evaluation",
        id: "leaf-86",
        discretion: "mandatory",
      },
    ],
  },
  {
    value: [612004000],
    name: "Treasury",
    id: "branch-15",
    discretion: null,
    children: [
      {
        value: [474146000],
        name: "Interest on the Public Debt",
        id: "leaf-279",
        discretion: "net interest",
      },
      {
        value: [82053000],
        name: "Internal Revenue Service",
        id: "leaf-275",
        discretion: "mandatory",
      },
      {
        value: [24495000],
        name: "Financial Management Service",
        id: "leaf-278",
        discretion: "net interest",
      },
      {
        value: [13285000],
        name: "Internal Revenue Service",
        id: "leaf-269",
        discretion: "discretionary",
      },
      {
        value: [9495000],
        name: "Departmental Offices",
        id: "leaf-273",
        discretion: "mandatory",
      },
      {
        value: [3841000],
        name: "Financial Management Service",
        id: "leaf-274",
        discretion: "mandatory",
      },
      {
        value: [3289000],
        name: "Internal Revenue Service",
        id: "leaf-280",
        discretion: "net interest",
      },
      {
        value: [510000],
        name: "Alcohol and Tobacco Tax and Trade Bureau",
        id: "leaf-270",
        discretion: "mandatory",
      },
      {
        value: [219000],
        name: "Financial Management Service",
        id: "leaf-268",
        discretion: "discretionary",
      },
      {
        value: [166000],
        name: "Departmental Offices",
        id: "leaf-266",
        discretion: "discretionary",
      },
      {
        value: [166000],
        name: "Bureau of the Public Debt",
        id: "leaf-264",
        discretion: "discretionary",
      },
      {
        value: [127000],
        name: "Bureau of the Public Debt",
        id: "leaf-271",
        discretion: "mandatory",
      },
      {
        value: [114000],
        name: "Financial Crimes Enforcement Network",
        id: "leaf-267",
        discretion: "discretionary",
      },
      {
        value: [98000],
        name: "Alcohol and Tobacco Tax and Trade Bureau",
        id: "leaf-263",
        discretion: "discretionary",
      },
    ],
  },
  {
    value: [148349000],
    name: "Agriculture",
    id: "branch-3",
    discretion: null,
    children: [
      {
        value: [104212000],
        name: "Food and Nutrition Service",
        id: "leaf-39",
        discretion: "mandatory",
      },
      {
        value: [9801000],
        name: "Farm Service Agency",
        id: "leaf-38",
        discretion: "mandatory",
      },
      {
        value: [7765000],
        name: "Food and Nutrition Service",
        id: "leaf-14",
        discretion: "discretionary",
      },
      {
        value: [5125000],
        name: "Forest Service",
        id: "leaf-17",
        discretion: "discretionary",
      },
      {
        value: [4592000],
        name: "Natural Resources Conservation Service",
        id: "leaf-44",
        discretion: "mandatory",
      },
      {
        value: [2981000],
        name: "Risk Management Agency",
        id: "leaf-47",
        discretion: "mandatory",
      },
      {
        value: [2124000],
        name: "Foreign Agricultural Service",
        id: "leaf-16",
        discretion: "discretionary",
      },
      {
        value: [1777000],
        name: "Farm Service Agency",
        id: "leaf-13",
        discretion: "discretionary",
      },
      {
        value: [1446000],
        name: "Rural Housing Service",
        id: "leaf-31",
        discretion: "discretionary",
      },
      {
        value: [1306000],
        name: "Agricultural Marketing Service",
        id: "leaf-33",
        discretion: "mandatory",
      },
      {
        value: [1209000],
        name: "National Institute of Food and Agriculture",
        id: "leaf-21",
        discretion: "discretionary",
      },
      {
        value: [1011000],
        name: "Food Safety and Inspection Service",
        id: "leaf-15",
        discretion: "discretionary",
      },
      {
        value: [914000],
        name: "Agricultural Research Service",
        id: "leaf-7",
        discretion: "discretionary",
      },
      {
        value: [838000],
        name: "Animal and Plant Health Inspection Service",
        id: "leaf-8",
        discretion: "discretionary",
      },
      {
        value: [695000],
        name: "Forest Service",
        id: "leaf-42",
        discretion: "mandatory",
      },
      {
        value: [577000],
        name: "Rural Utilities Service",
        id: "leaf-32",
        discretion: "discretionary",
      },
      {
        value: [412000],
        name: "Departmental Management",
        id: "leaf-10",
        discretion: "discretionary",
      },
      {
        value: [264000],
        name: "Animal and Plant Health Inspection Service",
        id: "leaf-35",
        discretion: "mandatory",
      },
      {
        value: [234000],
        name: "Rural Development",
        id: "leaf-30",
        discretion: "discretionary",
      },
      {
        value: [175000],
        name: "Rural Business_Cooperative Service",
        id: "leaf-48",
        discretion: "mandatory",
      },
      {
        value: [165000],
        name: "National Agricultural Statistics Service",
        id: "leaf-19",
        discretion: "discretionary",
      },
      {
        value: [134000],
        name: "National Institute of Food and Agriculture",
        id: "leaf-43",
        discretion: "mandatory",
      },
      {
        value: [99000],
        name: "Agricultural Marketing Service",
        id: "leaf-6",
        discretion: "discretionary",
      },
      {
        value: [91000],
        name: "Office of the Inspector General",
        id: "leaf-26",
        discretion: "discretionary",
      },
      {
        value: [86000],
        name: "Economic Research Service",
        id: "leaf-11",
        discretion: "discretionary",
      },
      {
        value: [82000],
        name: "Risk Management Agency",
        id: "leaf-28",
        discretion: "discretionary",
      },
      {
        value: [53000],
        name: "Office of the Secretary",
        id: "leaf-27",
        discretion: "discretionary",
      },
      {
        value: [46000],
        name: "Office of the General Counsel",
        id: "leaf-25",
        discretion: "discretionary",
      },
      {
        value: [44000],
        name: "Grain Inspection, Packers and Stockyards Administration",
        id: "leaf-18",
        discretion: "discretionary",
      },
      {
        value: [22000],
        name: "Departmental Management",
        id: "leaf-37",
        discretion: "mandatory",
      },
      {
        value: [18000],
        name: "Agricultural Research Service",
        id: "leaf-34",
        discretion: "mandatory",
      },
      {
        value: [15000],
        name: "National Appeals Division",
        id: "leaf-20",
        discretion: "discretionary",
      },
      {
        value: [15000],
        name: "Office of Chief Economist",
        id: "leaf-23",
        discretion: "discretionary",
      },
      {
        value: [10000],
        name: "Office of Communications",
        id: "leaf-24",
        discretion: "discretionary",
      },
      {
        value: [9000],
        name: "Food Safety and Inspection Service",
        id: "leaf-40",
        discretion: "mandatory",
      },
      {
        value: [1000],
        name: "Office of the Secretary",
        id: "leaf-46",
        discretion: "mandatory",
      },
      {
        value: [1000],
        name: "Office of Chief Economist",
        id: "leaf-45",
        discretion: "mandatory",
      },
    ],
  },
  {
    value: [132612000],
    name: "Labor",
    id: "branch-12",
    discretion: null,
    children: [
      {
        value: [117659000],
        name: "Employment and Training Administration",
        id: "leaf-218",
        discretion: "mandatory",
      },
      {
        value: [10000000],
        name: "Employment and Training Administration",
        id: "leaf-209",
        discretion: "discretionary",
      },
      {
        value: [2078000],
        name: "Office of Workers' Compensation Programs",
        id: "leaf-220",
        discretion: "mandatory",
      },
      {
        value: [583000],
        name: "Occupational Safety and Health Administration",
        id: "leaf-212",
        discretion: "discretionary",
      },
      {
        value: [578000],
        name: "Bureau of Labor Statistics",
        id: "leaf-205",
        discretion: "discretionary",
      },
      {
        value: [567000],
        name: "Departmental Management",
        id: "leaf-207",
        discretion: "discretionary",
      },
      {
        value: [384000],
        name: "Mine Safety and Health Administration",
        id: "leaf-211",
        discretion: "discretionary",
      },
      {
        value: [241000],
        name: "Wage and Hour Division",
        id: "leaf-216",
        discretion: "discretionary",
      },
      {
        value: [198000],
        name: "Employee Benefits Security Administration",
        id: "leaf-208",
        discretion: "discretionary",
      },
      {
        value: [123000],
        name: "Office of Workers' Compensation Programs",
        id: "leaf-215",
        discretion: "discretionary",
      },
      {
        value: [109000],
        name: "Office of Federal Contract Compliance Programs",
        id: "leaf-213",
        discretion: "discretionary",
      },
      {
        value: [51000],
        name: "Wage and Hour Division",
        id: "leaf-221",
        discretion: "mandatory",
      },
      {
        value: [41000],
        name: "Office of Labor Management Standards",
        id: "leaf-214",
        discretion: "discretionary",
      },
    ],
  },
  {
    value: [132359000],
    name: "Veterans Affairs",
    id: "branch-17",
    discretion: null,
    children: [
      {
        value: [70477000],
        name: "Benefits Programs",
        id: "leaf-310",
        discretion: "mandatory",
      },
      {
        value: [54438000],
        name: "Veterans Health Administration",
        id: "leaf-309",
        discretion: "discretionary",
      },
      {
        value: [7259000],
        name: "Departmental Administration",
        id: "leaf-308",
        discretion: "discretionary",
      },
      {
        value: [156000],
        name: "Benefits Programs",
        id: "leaf-306",
        discretion: "discretionary",
      },
      {
        value: [29000],
        name: "Veterans Health Administration",
        id: "leaf-312",
        discretion: "mandatory",
      },
    ],
  },
  {
    value: [129458000],
    name: "Transportation",
    id: "branch-16",
    discretion: null,
    children: [
      {
        value: [70546000],
        name: "Federal Highway Administration",
        id: "leaf-297",
        discretion: "mandatory",
      },
      {
        value: [22201000],
        name: "Federal Transit Administration",
        id: "leaf-300",
        discretion: "mandatory",
      },
      {
        value: [12883000],
        name: "Federal Aviation Administration",
        id: "leaf-282",
        discretion: "discretionary",
      },
      {
        value: [8046000],
        name: "Federal Railroad Administration",
        id: "leaf-299",
        discretion: "mandatory",
      },
      {
        value: [5774000],
        name: "Federal Aviation Administration",
        id: "leaf-296",
        discretion: "mandatory",
      },
      {
        value: [5000000],
        name: "National Infrastructure Bank",
        id: "leaf-303",
        discretion: "mandatory",
      },
      {
        value: [2050000],
        name: "Office of the Secretary",
        id: "leaf-304",
        discretion: "mandatory",
      },
      {
        value: [860000],
        name: "National Highway Traffic Safety Administration",
        id: "leaf-302",
        discretion: "mandatory",
      },
      {
        value: [606000],
        name: "Federal Motor Carrier Safety Administration",
        id: "leaf-298",
        discretion: "mandatory",
      },
      {
        value: [303000],
        name: "Maritime Administration",
        id: "leaf-287",
        discretion: "discretionary",
      },
      {
        value: [290000],
        name: "Office of the Secretary",
        id: "leaf-290",
        discretion: "discretionary",
      },
      {
        value: [192000],
        name: "Pipeline and Hazardous Materials Safety Administration",
        id: "leaf-291",
        discretion: "discretionary",
      },
      {
        value: [183000],
        name: "Federal Railroad Administration",
        id: "leaf-285",
        discretion: "discretionary",
      },
      {
        value: [175000],
        name: "Maritime Administration",
        id: "leaf-301",
        discretion: "mandatory",
      },
      {
        value: [150000],
        name: "Federal Transit Administration",
        id: "leaf-286",
        discretion: "discretionary",
      },
      {
        value: [89000],
        name: "Office of Inspector General",
        id: "leaf-289",
        discretion: "discretionary",
      },
      {
        value: [34000],
        name: "Saint Lawrence Seaway Development Corporation",
        id: "leaf-293",
        discretion: "discretionary",
      },
      {
        value: [30000],
        name: "Surface Transportation Board",
        id: "leaf-294",
        discretion: "discretionary",
      },
      {
        value: [28000],
        name: "Pipeline and Hazardous Materials Safety Administration",
        id: "leaf-305",
        discretion: "mandatory",
      },
      {
        value: [18000],
        name: "Research and Innovative Technology Administration",
        id: "leaf-292",
        discretion: "discretionary",
      },
    ],
  },
  {
    value: [93790000],
    name: "Education",
    id: "branch-6",
    discretion: null,
    children: [
      {
        value: [31433000],
        name: "Office of Federal Student Aid",
        id: "leaf-95",
        discretion: "discretionary",
      },
      {
        value: [20161000],
        name: "Office of Elementary and Secondary Education",
        id: "leaf-93",
        discretion: "discretionary",
      },
      {
        value: [12805000],
        name: "Office of Federal Student Aid",
        id: "leaf-103",
        discretion: "mandatory",
      },
      {
        value: [12647000],
        name: "Office of Special Education and Rehabilitative Services",
        id: "leaf-99",
        discretion: "discretionary",
      },
      {
        value: [4995000],
        name: "Office of Innovation and Improvement",
        id: "leaf-96",
        discretion: "discretionary",
      },
      {
        value: [3122000],
        name: "Office of Special Education and Rehabilitative Services",
        id: "leaf-106",
        discretion: "mandatory",
      },
      {
        value: [2533000],
        name: "Office of Postsecondary Education",
        id: "leaf-97",
        discretion: "discretionary",
      },
      {
        value: [1781000],
        name: "Office of Safe and Drug-Free Schools",
        id: "leaf-98",
        discretion: "discretionary",
      },
      {
        value: [1683000],
        name: "Office of Vocational and Adult Education",
        id: "leaf-100",
        discretion: "discretionary",
      },
      {
        value: [760000],
        name: "Institute of Education Sciences",
        id: "leaf-92",
        discretion: "discretionary",
      },
      {
        value: [750000],
        name: "Office of English Language Acquisition",
        id: "leaf-94",
        discretion: "discretionary",
      },
      {
        value: [654000],
        name: "Departmental Management",
        id: "leaf-91",
        discretion: "discretionary",
      },
      {
        value: [426000],
        name: "Office of Postsecondary Education",
        id: "leaf-105",
        discretion: "mandatory",
      },
      {
        value: [40000],
        name: "Office of Innovation and Improvement",
        id: "leaf-104",
        discretion: "mandatory",
      },
    ],
  },
  {
    value: [83502000],
    name: "Office of Personnel Management",
    id: "branch-28",
    discretion: null,
    children: [
      {
        value: [83239000],
        name: "Office of Personnel Management",
        id: "leaf-403",
        discretion: "mandatory",
      },
      {
        value: [263000],
        name: "Office of Personnel Management",
        id: "leaf-402",
        discretion: "discretionary",
      },
    ],
  },
  {
    value: [66476000],
    name: "Other",
    id: "branch-29",
    discretion: null,
    children: [
      {
        value: [18724000],
        name: "National Aeronautics and Space Administration",
        id: "leaf-443",
        discretion: "discretionary",
      },
      {
        value: [10000000],
        name: "Allowances",
        id: "leaf-476",
        discretion: "mandatory",
      },
      {
        value: [8973000],
        name: "Environmental Protection Agency",
        id: "leaf-424",
        discretion: "discretionary",
      },
      {
        value: [7768000],
        name: "National Science Foundation",
        id: "leaf-452",
        discretion: "discretionary",
      },
      {
        value: [5947000],
        name: "Postal Service",
        id: "leaf-499",
        discretion: "mandatory",
      },
      {
        value: [1900000],
        name: "National Credit Union Administration",
        id: "leaf-495",
        discretion: "mandatory",
      },
      {
        value: [1259000],
        name: "Corporation for National and Community Service",
        id: "leaf-417",
        discretion: "discretionary",
      },
      {
        value: [1125000],
        name: "Tennessee Valley Authority",
        id: "leaf-505",
        discretion: "mandatory",
      },
      {
        value: [1048000],
        name: "Smithsonian Institution",
        id: "leaf-469",
        discretion: "discretionary",
      },
      {
        value: [984000],
        name: "Small Business Administration",
        id: "leaf-468",
        discretion: "discretionary",
      },
      {
        value: [767000],
        name: "Broadcasting Board of Governors",
        id: "leaf-409",
        discretion: "discretionary",
      },
      {
        value: [592000],
        name: "Intelligence Community Management Account",
        id: "leaf-437",
        discretion: "discretionary",
      },
      {
        value: [514000],
        name: "Central Intelligence Agency",
        id: "leaf-480",
        discretion: "mandatory",
      },
      {
        value: [451000],
        name: "Corporation for Public Broadcasting",
        id: "leaf-418",
        discretion: "discretionary",
      },
      {
        value: [450000],
        name: "Legal Services Corporation",
        id: "leaf-439",
        discretion: "discretionary",
      },
      {
        value: [386000],
        name: "Equal Employment Opportunity Commission",
        id: "leaf-425",
        discretion: "discretionary",
      },
      {
        value: [347000],
        name: "Postal Service",
        id: "leaf-464",
        discretion: "discretionary",
      },
      {
        value: [333000],
        name: "Federal Drug Control Programs",
        id: "leaf-427",
        discretion: "discretionary",
      },
      {
        value: [329000],
        name: "Bureau of Consumer Financial Protection",
        id: "leaf-479",
        discretion: "mandatory",
      },
      {
        value: [288000],
        name: "Securities Investor Protection Corporation",
        id: "leaf-501",
        discretion: "mandatory",
      },
      {
        value: [288000],
        name: "National Labor Relations Board",
        id: "leaf-449",
        discretion: "discretionary",
      },
      {
        value: [258000],
        name: "Court Services and Offender Supervision Agency for the District",
        id: "leaf-419",
        discretion: "discretionary",
      },
      {
        value: [248000],
        name: "National Science Foundation",
        id: "leaf-496",
        discretion: "mandatory",
      },
      {
        value: [243000],
        name: "Institute of Museum and Library Services",
        id: "leaf-436",
        discretion: "discretionary",
      },
      {
        value: [227000],
        name: "Federal Housing Finance Agency",
        id: "leaf-486",
        discretion: "mandatory",
      },
      {
        value: [216000],
        name: "Affordable Housing Program",
        id: "leaf-475",
        discretion: "mandatory",
      },
      {
        value: [215000],
        name: "Neighborhood Reinvestment Corporation",
        id: "leaf-454",
        discretion: "discretionary",
      },
      {
        value: [213000],
        name: "Public Company Accounting Oversight Board",
        id: "leaf-500",
        discretion: "mandatory",
      },
      {
        value: [197000],
        name: "Federal Trade Commission",
        id: "leaf-433",
        discretion: "discretionary",
      },
      {
        value: [191000],
        name: "Commodity Futures Trading Commission",
        id: "leaf-415",
        discretion: "discretionary",
      },
      {
        value: [150000],
        name: "Patient-Centered Outcomes Research Trust Fund",
        id: "leaf-498",
        discretion: "mandatory",
      },
      {
        value: [146000],
        name: "National Endowment for the Humanities",
        id: "leaf-448",
        discretion: "discretionary",
      },
      {
        value: [146000],
        name: "National Endowment for the Arts",
        id: "leaf-447",
        discretion: "discretionary",
      },
      {
        value: [128000],
        name: "Nuclear Regulatory Commission",
        id: "leaf-456",
        discretion: "discretionary",
      },
      {
        value: [122000],
        name: "Consumer Product Safety Commission",
        id: "leaf-416",
        discretion: "discretionary",
      },
      {
        value: [102000],
        name: "National Transportation Safety Board",
        id: "leaf-453",
        discretion: "discretionary",
      },
      {
        value: [100000],
        name: "Electric Reliability Organization",
        id: "leaf-483",
        discretion: "mandatory",
      },
      {
        value: [100000],
        name: "Corporation for Travel Promotion",
        id: "leaf-482",
        discretion: "mandatory",
      },
      {
        value: [88000],
        name: "Civilian Property Realignment Board",
        id: "leaf-412",
        discretion: "discretionary",
      },
      {
        value: [87000],
        name: "International Trade Commission",
        id: "leaf-438",
        discretion: "discretionary",
      },
      {
        value: [76000],
        name: "Appalachian Regional Commission",
        id: "leaf-408",
        discretion: "discretionary",
      },
      {
        value: [67000],
        name: "Federal Election Commission",
        id: "leaf-428",
        discretion: "discretionary",
      },
      {
        value: [56000],
        name: "United States Court of Appeals for Veterans Claims",
        id: "leaf-471",
        discretion: "discretionary",
      },
      {
        value: [53000],
        name: "United States Holocaust Memorial Museum",
        id: "leaf-472",
        discretion: "discretionary",
      },
      {
        value: [48000],
        name: "Federal Mediation and Conciliation Service",
        id: "leaf-431",
        discretion: "discretionary",
      },
      {
        value: [43000],
        name: "United States Institute of Peace",
        id: "leaf-473",
        discretion: "discretionary",
      },
      {
        value: [42000],
        name: "Merit Systems Protection Board",
        id: "leaf-441",
        discretion: "discretionary",
      },
      {
        value: [41000],
        name: "Standard Setting Body",
        id: "leaf-503",
        discretion: "mandatory",
      },
      {
        value: [33000],
        name: "United Mine Workers of America Benefit Funds",
        id: "leaf-507",
        discretion: "mandatory",
      },
      {
        value: [29000],
        name: "Defense Nuclear Facilities Safety Board",
        id: "leaf-420",
        discretion: "discretionary",
      },
      {
        value: [26000],
        name: "Federal Maritime Commission",
        id: "leaf-430",
        discretion: "discretionary",
      },
      {
        value: [26000],
        name: "Federal Labor Relations Authority",
        id: "leaf-429",
        discretion: "discretionary",
      },
      {
        value: [22000],
        name: "National Railroad Passenger Corporation Office of Inspector Gene",
        id: "leaf-451",
        discretion: "discretionary",
      },
      {
        value: [22000],
        name: "Federal Mine Safety and Health Review Commission",
        id: "leaf-432",
        discretion: "discretionary",
      },
      {
        value: [20000],
        name: "Corporation for National and Community Service",
        id: "leaf-481",
        discretion: "mandatory",
      },
      {
        value: [19000],
        name: "Office of Special Counsel",
        id: "leaf-461",
        discretion: "discretionary",
      },
      {
        value: [16000],
        name: "Denali Commission",
        id: "leaf-422",
        discretion: "discretionary",
      },
      {
        value: [14000],
        name: "National Mediation Board",
        id: "leaf-450",
        discretion: "discretionary",
      },
      {
        value: [14000],
        name: "Office of Government Ethics",
        id: "leaf-459",
        discretion: "discretionary",
      },
      {
        value: [13000],
        name: "Delta Regional Authority",
        id: "leaf-421",
        discretion: "discretionary",
      },
      {
        value: [13000],
        name: "Occupational Safety and Health Review Commission",
        id: "leaf-458",
        discretion: "discretionary",
      },
      {
        value: [12000],
        name: "Presidio Trust",
        id: "leaf-465",
        discretion: "discretionary",
      },
      {
        value: [11000],
        name: "Election Assistance Commission",
        id: "leaf-423",
        discretion: "discretionary",
      },
      {
        value: [11000],
        name: "Chemical Safety and Hazard Investigation Board",
        id: "leaf-410",
        discretion: "discretionary",
      },
      {
        value: [10000],
        name: "Office of Navajo and Hopi Indian Relocation",
        id: "leaf-460",
        discretion: "discretionary",
      },
      {
        value: [9000],
        name: "Institute of American Indian and Alaska Native Culture and Arts",
        id: "leaf-435",
        discretion: "discretionary",
      },
      {
        value: [9000],
        name: "Commission on Civil Rights",
        id: "leaf-414",
        discretion: "discretionary",
      },
      {
        value: [8000],
        name: "National Capital Planning Commission",
        id: "leaf-444",
        discretion: "discretionary",
      },
      {
        value: [6000],
        name: "Advisory Council on Historic Preservation",
        id: "leaf-406",
        discretion: "discretionary",
      },
      {
        value: [6000],
        name: "Morris K. Udall and Stewart L. Udall Foundation",
        id: "leaf-442",
        discretion: "discretionary",
      },
      {
        value: [5000],
        name: "State Justice Institute",
        id: "leaf-470",
        discretion: "discretionary",
      },
      {
        value: [4000],
        name: "United States Interagency Council on Homelessness",
        id: "leaf-474",
        discretion: "discretionary",
      },
      {
        value: [4000],
        name: "Barry Goldwater Scholarship and Excellence in Education Foundati",
        id: "leaf-477",
        discretion: "mandatory",
      },
      {
        value: [4000],
        name: "Office of the Fed Coordinator for Alaska Natural Gas Transportat",
        id: "leaf-462",
        discretion: "discretionary",
      },
      {
        value: [3000],
        name: "Japan-United States Friendship Commission",
        id: "leaf-491",
        discretion: "mandatory",
      },
      {
        value: [3000],
        name: "Harry S Truman Scholarship Foundation",
        id: "leaf-489",
        discretion: "mandatory",
      },
      {
        value: [3000],
        name: "National Council on Disability",
        id: "leaf-445",
        discretion: "discretionary",
      },
      {
        value: [3000],
        name: "Marine Mammal Commission",
        id: "leaf-440",
        discretion: "discretionary",
      },
      {
        value: [3000],
        name: "Nuclear Waste Technical Review Board",
        id: "leaf-457",
        discretion: "discretionary",
      },
      {
        value: [3000],
        name: "Administrative Conference of the United States",
        id: "leaf-405",
        discretion: "discretionary",
      },
      {
        value: [2000],
        name: "Northern Border Regional Commission",
        id: "leaf-455",
        discretion: "discretionary",
      },
      {
        value: [2000],
        name: "James Madison Memorial Fellowship Foundation",
        id: "leaf-490",
        discretion: "mandatory",
      },
      {
        value: [2000],
        name: "National Credit Union Administration",
        id: "leaf-446",
        discretion: "discretionary",
      },
      {
        value: [2000],
        name: "Privacy and Civil Liberties Oversight Board",
        id: "leaf-466",
        discretion: "discretionary",
      },
      {
        value: [2000],
        name: "Commission of Fine Arts",
        id: "leaf-413",
        discretion: "discretionary",
      },
      {
        value: [2000],
        name: "United States Court of Appeals for Veterans Claims",
        id: "leaf-508",
        discretion: "mandatory",
      },
      {
        value: [1000],
        name: "Morris K. Udall and Stewart L. Udall Foundation",
        id: "leaf-493",
        discretion: "mandatory",
      },
      {
        value: [1000],
        name: "Christopher Columbus Fellowship Foundation",
        id: "leaf-411",
        discretion: "discretionary",
      },
      {
        value: [1000],
        name: "Public Company Accounting Oversight Board",
        id: "leaf-467",
        discretion: "discretionary",
      },
      {
        value: [1000],
        name: "Other Commissions and Boards",
        id: "leaf-463",
        discretion: "discretionary",
      },
    ],
  },
  {
    value: [58663000],
    name: "Other Defense Civil Programs",
    id: "branch-30",
    discretion: null,
    children: [
      {
        value: [48455000],
        name: "Military Retirement",
        id: "leaf-520",
        discretion: "mandatory",
      },
      {
        value: [9917000],
        name: "Retiree Health Care",
        id: "leaf-521",
        discretion: "mandatory",
      },
      {
        value: [77000],
        name: "American Battle Monuments Commission",
        id: "leaf-513",
        discretion: "discretionary",
      },
      {
        value: [76000],
        name: "Educational Benefits",
        id: "leaf-519",
        discretion: "mandatory",
      },
      {
        value: [68000],
        name: "Armed Forces Retirement Home",
        id: "leaf-514",
        discretion: "discretionary",
      },
      {
        value: [46000],
        name: "Cemeterial Expenses",
        id: "leaf-515",
        discretion: "discretionary",
      },
      {
        value: [24000],
        name: "Selective Service System",
        id: "leaf-516",
        discretion: "discretionary",
      },
    ],
  },
  {
    value: [52092000],
    name: "Housing and Urban Development",
    id: "branch-10",
    discretion: null,
    children: [
      {
        value: [36186000],
        name: "Public and Indian Housing Programs",
        id: "leaf-178",
        discretion: "discretionary",
      },
      {
        value: [8211000],
        name: "Community Planning and Development",
        id: "leaf-169",
        discretion: "discretionary",
      },
      {
        value: [4484000],
        name: "Housing Programs",
        id: "leaf-182",
        discretion: "mandatory",
      },
      {
        value: [1791000],
        name: "Management and Administration",
        id: "leaf-174",
        discretion: "discretionary",
      },
      {
        value: [1001000],
        name: "Community Planning and Development",
        id: "leaf-179",
        discretion: "mandatory",
      },
      {
        value: [150000],
        name: "Office of Sustainable Housing and Communities",
        id: "leaf-176",
        discretion: "discretionary",
      },
      {
        value: [140000],
        name: "Office of Lead Hazard Control and Healthy Homes",
        id: "leaf-175",
        discretion: "discretionary",
      },
      {
        value: [72000],
        name: "Fair Housing and Equal Opportunity",
        id: "leaf-171",
        discretion: "discretionary",
      },
      {
        value: [57000],
        name: "Policy Development and Research",
        id: "leaf-177",
        discretion: "discretionary",
      },
    ],
  },
  {
    value: [50045000],
    name: "Homeland Security",
    id: "branch-9",
    discretion: null,
    children: [
      {
        value: [10493000],
        name: "Customs and Border Protection",
        id: "leaf-147",
        discretion: "discretionary",
      },
      {
        value: [8935000],
        name: "United States Coast Guard",
        id: "leaf-158",
        discretion: "discretionary",
      },
      {
        value: [6790000],
        name: "Federal Emergency Management Agency",
        id: "leaf-151",
        discretion: "discretionary",
      },
      {
        value: [5495000],
        name: "Immigration and Customs Enforcement",
        id: "leaf-153",
        discretion: "discretionary",
      },
      {
        value: [5114000],
        name: "Transportation Security Administration",
        id: "leaf-157",
        discretion: "discretionary",
      },
      {
        value: [2534000],
        name: "Citizenship and Immigration Services",
        id: "leaf-160",
        discretion: "mandatory",
      },
      {
        value: [1699000],
        name: "United States Secret Service",
        id: "leaf-159",
        discretion: "discretionary",
      },
      {
        value: [1662000],
        name: "United States Coast Guard",
        id: "leaf-166",
        discretion: "mandatory",
      },
      {
        value: [1471000],
        name: "Customs and Border Protection",
        id: "leaf-161",
        discretion: "mandatory",
      },
      {
        value: [1428000],
        name: "National Protection and Programs Directorate",
        id: "leaf-154",
        discretion: "discretionary",
      },
      {
        value: [1302000],
        name: "Departmental Management and Operations",
        id: "leaf-149",
        discretion: "discretionary",
      },
      {
        value: [1177000],
        name: "Science and Technology",
        id: "leaf-156",
        discretion: "discretionary",
      },
      {
        value: [365000],
        name: "Citizenship and Immigration Services",
        id: "leaf-146",
        discretion: "discretionary",
      },
      {
        value: [331000],
        name: "Domestic Nuclear Detection Office",
        id: "leaf-150",
        discretion: "discretionary",
      },
      {
        value: [311000],
        name: "Immigration and Customs Enforcement",
        id: "leaf-164",
        discretion: "mandatory",
      },
      {
        value: [276000],
        name: "Federal Law Enforcement Training Center",
        id: "leaf-152",
        discretion: "discretionary",
      },
      {
        value: [250000],
        name: "Transportation Security Administration",
        id: "leaf-165",
        discretion: "mandatory",
      },
      {
        value: [245000],
        name: "United States Secret Service",
        id: "leaf-167",
        discretion: "mandatory",
      },
      {
        value: [144000],
        name: "Office of the Inspector General",
        id: "leaf-155",
        discretion: "discretionary",
      },
      {
        value: [23000],
        name: "Federal Emergency Management Agency",
        id: "leaf-163",
        discretion: "mandatory",
      },
    ],
  },
  {
    value: [41915000],
    name: "International Assistance Programs",
    id: "branch-24",
    discretion: null,
    children: [
      {
        value: [15965000],
        name: "International Security Assistance",
        id: "leaf-353",
        discretion: "discretionary",
      },
      {
        value: [14257000],
        name: "Military Sales Program",
        id: "leaf-362",
        discretion: "mandatory",
      },
      {
        value: [6246000],
        name: "Agency for International Development",
        id: "leaf-350",
        discretion: "discretionary",
      },
      {
        value: [3713000],
        name: "Multilateral Assistance",
        id: "leaf-355",
        discretion: "discretionary",
      },
      {
        value: [1125000],
        name: "Millennium Challenge Corporation",
        id: "leaf-354",
        discretion: "discretionary",
      },
      {
        value: [440000],
        name: "Peace Corps",
        id: "leaf-357",
        discretion: "discretionary",
      },
      {
        value: [70000],
        name: "Overseas Private Investment Corporation",
        id: "leaf-363",
        discretion: "mandatory",
      },
      {
        value: [56000],
        name: "Trade and Development Agency",
        id: "leaf-358",
        discretion: "discretionary",
      },
      {
        value: [24000],
        name: "African Development Foundation",
        id: "leaf-349",
        discretion: "discretionary",
      },
      {
        value: [19000],
        name: "Inter-American Foundation",
        id: "leaf-351",
        discretion: "discretionary",
      },
    ],
  },
  {
    value: [35403000],
    name: "Justice",
    id: "branch-11",
    discretion: null,
    children: [
      {
        value: [8076000],
        name: "Federal Bureau of Investigation",
        id: "leaf-188",
        discretion: "discretionary",
      },
      {
        value: [7808000],
        name: "Office of Justice Programs",
        id: "leaf-202",
        discretion: "mandatory",
      },
      {
        value: [6791000],
        name: "Federal Prison System",
        id: "leaf-189",
        discretion: "discretionary",
      },
      {
        value: [3909000],
        name: "Legal Activities and U.S. Marshals",
        id: "leaf-192",
        discretion: "discretionary",
      },
      {
        value: [2323000],
        name: "Legal Activities and U.S. Marshals",
        id: "leaf-201",
        discretion: "mandatory",
      },
      {
        value: [2293000],
        name: "General Administration",
        id: "leaf-190",
        discretion: "discretionary",
      },
      {
        value: [2012000],
        name: "Drug Enforcement Administration",
        id: "leaf-187",
        discretion: "discretionary",
      },
      {
        value: [1147000],
        name: "Bureau of Alcohol, Tobacco, Firearms, and Explosives",
        id: "leaf-185",
        discretion: "discretionary",
      },
      {
        value: [541000],
        name: "Interagency Law Enforcement",
        id: "leaf-191",
        discretion: "discretionary",
      },
      {
        value: [282000],
        name: "Drug Enforcement Administration",
        id: "leaf-198",
        discretion: "mandatory",
      },
      {
        value: [120000],
        name: "Radiation Exposure Compensation",
        id: "leaf-203",
        discretion: "mandatory",
      },
      {
        value: [88000],
        name: "National Security Division",
        id: "leaf-193",
        discretion: "discretionary",
      },
      {
        value: [13000],
        name: "United States Parole Commission",
        id: "leaf-195",
        discretion: "discretionary",
      },
    ],
  },
  {
    value: [32746000],
    name: "State",
    id: "branch-13",
    discretion: null,
    children: [
      {
        value: [14747000],
        name: "Administration of Foreign Affairs",
        id: "leaf-223",
        discretion: "discretionary",
      },
      {
        value: [13080000],
        name: "Other",
        id: "leaf-227",
        discretion: "discretionary",
      },
      {
        value: [3539000],
        name: "International Organizations and Conferences",
        id: "leaf-226",
        discretion: "discretionary",
      },
      {
        value: [1257000],
        name: "Administration of Foreign Affairs",
        id: "leaf-228",
        discretion: "mandatory",
      },
      {
        value: [122000],
        name: "International Commissions",
        id: "leaf-225",
        discretion: "discretionary",
      },
      {
        value: [1000],
        name: "Other",
        id: "leaf-230",
        discretion: "mandatory",
      },
    ],
  },
  {
    value: [30779000],
    name: "Energy",
    id: "branch-7",
    discretion: null,
    children: [
      {
        value: [11836000],
        name: "Energy Programs",
        id: "leaf-110",
        discretion: "discretionary",
      },
      {
        value: [11712000],
        name: "National Nuclear Security Administration",
        id: "leaf-112",
        discretion: "discretionary",
      },
      {
        value: [6267000],
        name: "Environmental and Other Defense Activities",
        id: "leaf-111",
        discretion: "discretionary",
      },
      {
        value: [604000],
        name: "Power Marketing Administration",
        id: "leaf-116",
        discretion: "mandatory",
      },
      {
        value: [171000],
        name: "Departmental Administration",
        id: "leaf-109",
        discretion: "discretionary",
      },
      {
        value: [103000],
        name: "Energy Programs",
        id: "leaf-115",
        discretion: "mandatory",
      },
      {
        value: [86000],
        name: "Power Marketing Administration",
        id: "leaf-113",
        discretion: "discretionary",
      },
    ],
  },
  {
    value: [17863000],
    name: "Interior",
    id: "branch-14",
    discretion: null,
    children: [
      {
        value: [2892000],
        name: "National Park Service",
        id: "leaf-241",
        discretion: "discretionary",
      },
      {
        value: [2501000],
        name: "Bureau of Indian Affairs and Bureau of Indian Education",
        id: "leaf-232",
        discretion: "discretionary",
      },
      {
        value: [2117000],
        name: "Departmental Offices",
        id: "leaf-254",
        discretion: "mandatory",
      },
      {
        value: [1695000],
        name: "United States Fish and Wildlife Service",
        id: "leaf-246",
        discretion: "discretionary",
      },
      {
        value: [1132000],
        name: "Bureau of Land Management",
        id: "leaf-233",
        discretion: "discretionary",
      },
      {
        value: [1118000],
        name: "United States Geological Survey",
        id: "leaf-247",
        discretion: "discretionary",
      },
      {
        value: [1018000],
        name: "Bureau of Reclamation",
        id: "leaf-235",
        discretion: "discretionary",
      },
      {
        value: [996000],
        name: "United States Fish and Wildlife Service",
        id: "leaf-260",
        discretion: "mandatory",
      },
      {
        value: [911000],
        name: "Department-Wide Programs",
        id: "leaf-238",
        discretion: "discretionary",
      },
      {
        value: [538000],
        name: "Office of Surface Mining Reclamation and Enforcement",
        id: "leaf-258",
        discretion: "mandatory",
      },
      {
        value: [437000],
        name: "Department-Wide Programs",
        id: "leaf-253",
        discretion: "mandatory",
      },
      {
        value: [405000],
        name: "Insular Affairs",
        id: "leaf-255",
        discretion: "mandatory",
      },
      {
        value: [395000],
        name: "National Park Service",
        id: "leaf-257",
        discretion: "mandatory",
      },
      {
        value: [358000],
        name: "Office of the Special Trustee for American Indians",
        id: "leaf-259",
        discretion: "mandatory",
      },
      {
        value: [242000],
        name: "Departmental Offices",
        id: "leaf-239",
        discretion: "discretionary",
      },
      {
        value: [194000],
        name: "Bureau of Reclamation",
        id: "leaf-251",
        discretion: "mandatory",
      },
      {
        value: [152000],
        name: "Office of the Special Trustee for American Indians",
        id: "leaf-245",
        discretion: "discretionary",
      },
      {
        value: [146000],
        name: "Office of Surface Mining Reclamation and Enforcement",
        id: "leaf-243",
        discretion: "discretionary",
      },
      {
        value: [133000],
        name: "Bureau of Land Management",
        id: "leaf-249",
        discretion: "mandatory",
      },
      {
        value: [132000],
        name: "Bureau of Ocean Energy Management, Regulation and Enforcement",
        id: "leaf-234",
        discretion: "discretionary",
      },
      {
        value: [106000],
        name: "Bureau of Indian Affairs and Bureau of Indian Education",
        id: "leaf-248",
        discretion: "mandatory",
      },
      {
        value: [69000],
        name: "Insular Affairs",
        id: "leaf-240",
        discretion: "discretionary",
      },
      {
        value: [68000],
        name: "Office of the Solicitor",
        id: "leaf-244",
        discretion: "discretionary",
      },
      {
        value: [49000],
        name: "Office of Inspector General",
        id: "leaf-242",
        discretion: "discretionary",
      },
      {
        value: [33000],
        name: "Central Utah Project",
        id: "leaf-236",
        discretion: "discretionary",
      },
      {
        value: [17000],
        name: "National Indian Gaming Commission",
        id: "leaf-256",
        discretion: "mandatory",
      },
      {
        value: [8000],
        name: "Bureau of Ocean Energy Management, Regulation and Enforcement",
        id: "leaf-250",
        discretion: "mandatory",
      },
      {
        value: [1000],
        name: "United States Geological Survey",
        id: "leaf-261",
        discretion: "mandatory",
      },
    ],
  },
  {
    value: [11570000],
    name: "Federal Communications Commission",
    id: "branch-20",
    discretion: null,
    children: [
      {
        value: [11570000],
        name: "Federal Communications Commission",
        id: "leaf-334",
        discretion: "mandatory",
      },
    ],
  },
  {
    value: [10449000],
    name: "Commerce",
    id: "branch-4",
    discretion: null,
    children: [
      {
        value: [5510000],
        name: "National Oceanic and Atmospheric Administration",
        id: "leaf-61",
        discretion: "discretionary",
      },
      {
        value: [1400000],
        name: "National Telecommunications and Information Administration",
        id: "leaf-71",
        discretion: "mandatory",
      },
      {
        value: [1025000],
        name: "Bureau of the Census",
        id: "leaf-53",
        discretion: "discretionary",
      },
      {
        value: [1004000],
        name: "National Institute of Standards and Technology",
        id: "leaf-60",
        discretion: "discretionary",
      },
      {
        value: [517000],
        name: "International Trade Administration",
        id: "leaf-58",
        discretion: "discretionary",
      },
      {
        value: [325000],
        name: "Economic Development Administration",
        id: "leaf-57",
        discretion: "discretionary",
      },
      {
        value: [113000],
        name: "Economic and Statistical Analysis",
        id: "leaf-56",
        discretion: "discretionary",
      },
      {
        value: [111000],
        name: "National Oceanic and Atmospheric Administration",
        id: "leaf-70",
        discretion: "mandatory",
      },
      {
        value: [111000],
        name: "Bureau of Industry and Security",
        id: "leaf-52",
        discretion: "discretionary",
      },
      {
        value: [100000],
        name: "National Institute of Standards and Technology",
        id: "leaf-69",
        discretion: "mandatory",
      },
      {
        value: [95000],
        name: "Departmental Management",
        id: "leaf-55",
        discretion: "discretionary",
      },
      {
        value: [50000],
        name: "National Telecommunications and Information Administration",
        id: "leaf-62",
        discretion: "discretionary",
      },
      {
        value: [32000],
        name: "Minority Business Development Agency",
        id: "leaf-59",
        discretion: "discretionary",
      },
      {
        value: [30000],
        name: "Bureau of the Census",
        id: "leaf-64",
        discretion: "mandatory",
      },
      {
        value: [20000],
        name: "Economic Development Administration",
        id: "leaf-67",
        discretion: "mandatory",
      },
      {
        value: [5000],
        name: "International Trade Administration",
        id: "leaf-68",
        discretion: "mandatory",
      },
      {
        value: [1000],
        name: "Departmental Management",
        id: "leaf-66",
        discretion: "mandatory",
      },
    ],
  },
  {
    value: [8284000],
    name: "Judicial Branch",
    id: "branch-25",
    discretion: null,
    children: [
      {
        value: [6580000],
        name: "Courts of Appeals, District Courts, and other Judicial Services",
        id: "leaf-366",
        discretion: "discretionary",
      },
      {
        value: [1177000],
        name: "Courts of Appeals, District Courts, and other Judicial Services",
        id: "leaf-372",
        discretion: "mandatory",
      },
      {
        value: [248000],
        name: "Judicial Retirement Funds",
        id: "leaf-374",
        discretion: "mandatory",
      },
      {
        value: [89000],
        name: "Administrative Office of the United States Courts",
        id: "leaf-365",
        discretion: "discretionary",
      },
      {
        value: [83000],
        name: "Supreme Court of the United States",
        id: "leaf-368",
        discretion: "discretionary",
      },
      {
        value: [33000],
        name: "United States Court of Appeals for the Federal Circuit",
        id: "leaf-369",
        discretion: "discretionary",
      },
      {
        value: [29000],
        name: "Federal Judicial Center",
        id: "leaf-367",
        discretion: "discretionary",
      },
      {
        value: [21000],
        name: "United States Court of International Trade",
        id: "leaf-370",
        discretion: "discretionary",
      },
      {
        value: [18000],
        name: "United States Sentencing Commission",
        id: "leaf-371",
        discretion: "discretionary",
      },
      {
        value: [2000],
        name: "United States Court of Appeals for the Federal Circuit",
        id: "leaf-376",
        discretion: "mandatory",
      },
      {
        value: [2000],
        name: "Supreme Court of the United States",
        id: "leaf-375",
        discretion: "mandatory",
      },
      {
        value: [2000],
        name: "United States Court of International Trade",
        id: "leaf-377",
        discretion: "mandatory",
      },
    ],
  },
  {
    value: [7115000],
    name: "Railroad Retirement Board",
    id: "branch-31",
    discretion: null,
    children: [
      {
        value: [6945000],
        name: "Railroad Retirement Board",
        id: "leaf-524",
        discretion: "mandatory",
      },
      {
        value: [170000],
        name: "Railroad Retirement Board",
        id: "leaf-523",
        discretion: "discretionary",
      },
    ],
  },
  {
    value: [5173000],
    name: "Legislative Branch",
    id: "branch-26",
    discretion: null,
    children: [
      {
        value: [1334000],
        name: "House of Representatives",
        id: "leaf-384",
        discretion: "discretionary",
      },
      {
        value: [971000],
        name: "Senate",
        id: "leaf-389",
        discretion: "discretionary",
      },
      {
        value: [694000],
        name: "Architect of the Capitol",
        id: "leaf-378",
        discretion: "discretionary",
      },
      {
        value: [667000],
        name: "Library of Congress",
        id: "leaf-387",
        discretion: "discretionary",
      },
      {
        value: [557000],
        name: "Government Accountability Office",
        id: "leaf-382",
        discretion: "discretionary",
      },
      {
        value: [387000],
        name: "Capitol Police",
        id: "leaf-380",
        discretion: "discretionary",
      },
      {
        value: [148000],
        name: "Government Printing Office",
        id: "leaf-383",
        discretion: "discretionary",
      },
      {
        value: [130000],
        name: "Legislative Branch Boards and Commissions",
        id: "leaf-386",
        discretion: "discretionary",
      },
      {
        value: [101000],
        name: "House of Representatives",
        id: "leaf-392",
        discretion: "mandatory",
      },
      {
        value: [60000],
        name: "United States Tax Court",
        id: "leaf-390",
        discretion: "discretionary",
      },
      {
        value: [47000],
        name: "Congressional Budget Office",
        id: "leaf-381",
        discretion: "discretionary",
      },
      {
        value: [33000],
        name: "Senate",
        id: "leaf-396",
        discretion: "mandatory",
      },
      {
        value: [20000],
        name: "Joint Items",
        id: "leaf-385",
        discretion: "discretionary",
      },
      {
        value: [12000],
        name: "Botanic Garden",
        id: "leaf-379",
        discretion: "discretionary",
      },
      {
        value: [6000],
        name: "Library of Congress",
        id: "leaf-395",
        discretion: "mandatory",
      },
      {
        value: [5000],
        name: "Office of Compliance",
        id: "leaf-388",
        discretion: "discretionary",
      },
      {
        value: [1000],
        name: "United States Tax Court",
        id: "leaf-397",
        discretion: "mandatory",
      },
    ],
  },
  {
    value: [4584000],
    name: "Corps of Engineers--Civil Works",
    id: "branch-2",
    discretion: null,
    children: [
      {
        value: [4574000],
        name: "Corps of Engineers--Civil Works",
        id: "leaf-3",
        discretion: "discretionary",
      },
      {
        value: [10000],
        name: "Corps of Engineers--Civil Works",
        id: "leaf-4",
        discretion: "mandatory",
      },
    ],
  },
  {
    value: [1070000],
    name: "District of Columbia",
    id: "branch-18",
    discretion: null,
    children: [
      {
        value: [603000],
        name: "District of Columbia General and Special Payments",
        id: "leaf-317",
        discretion: "mandatory",
      },
      {
        value: [284000],
        name: "District of Columbia Courts",
        id: "leaf-314",
        discretion: "discretionary",
      },
      {
        value: [174000],
        name: "District of Columbia General and Special Payments",
        id: "leaf-315",
        discretion: "discretionary",
      },
      {
        value: [9000],
        name: "District of Columbia Courts",
        id: "leaf-316",
        discretion: "mandatory",
      },
    ],
  },
  {
    value: [915000],
    name: "Federal Deposit Insurance Corporation",
    id: "branch-21",
    discretion: null,
    children: [
      {
        value: [855000],
        name: "Orderly Liquidation",
        id: "leaf-340",
        discretion: "mandatory",
      },
      {
        value: [45000],
        name: "FDIC_Office of Inspector General",
        id: "leaf-337",
        discretion: "discretionary",
      },
      {
        value: [15000],
        name: "FSLIC Resolution",
        id: "leaf-339",
        discretion: "mandatory",
      },
    ],
  },
  {
    value: [653000],
    name: "General Services Administration",
    id: "branch-23",
    discretion: null,
    children: [
      {
        value: [332000],
        name: "General Activities",
        id: "leaf-342",
        discretion: "discretionary",
      },
      {
        value: [286000],
        name: "Real Property Activities",
        id: "leaf-344",
        discretion: "discretionary",
      },
      {
        value: [13000],
        name: "Supply and Technology Activities",
        id: "leaf-348",
        discretion: "mandatory",
      },
      {
        value: [12000],
        name: "General Activities",
        id: "leaf-345",
        discretion: "mandatory",
      },
      {
        value: [10000],
        name: "Real Property Activities",
        id: "leaf-347",
        discretion: "mandatory",
      },
    ],
  },
  {
    value: [569000],
    name: "Executive Office of the President",
    id: "branch-19",
    discretion: null,
    children: [
      {
        value: [116000],
        name: "Office of Administration",
        id: "leaf-323",
        discretion: "discretionary",
      },
      {
        value: [100000],
        name: "Unanticipated Needs",
        id: "leaf-332",
        discretion: "mandatory",
      },
      {
        value: [92000],
        name: "Office of Management and Budget",
        id: "leaf-324",
        discretion: "discretionary",
      },
      {
        value: [81000],
        name: "Unanticipated Needs",
        id: "leaf-330",
        discretion: "discretionary",
      },
      {
        value: [59000],
        name: "The White House",
        id: "leaf-329",
        discretion: "discretionary",
      },
      {
        value: [51000],
        name: "Office of the United States Trade Representative",
        id: "leaf-327",
        discretion: "discretionary",
      },
      {
        value: [23000],
        name: "Office of National Drug Control Policy",
        id: "leaf-325",
        discretion: "discretionary",
      },
      {
        value: [15000],
        name: "Executive Residence at the White House",
        id: "leaf-321",
        discretion: "discretionary",
      },
      {
        value: [13000],
        name: "National Security Council and Homeland Security Council",
        id: "leaf-322",
        discretion: "discretionary",
      },
      {
        value: [7000],
        name: "Office of Science and Technology Policy",
        id: "leaf-326",
        discretion: "discretionary",
      },
      {
        value: [5000],
        name: "Special Assistance to the President and the Official Residence",
        id: "leaf-328",
        discretion: "discretionary",
      },
      {
        value: [4000],
        name: "Council of Economic Advisers",
        id: "leaf-319",
        discretion: "discretionary",
      },
      {
        value: [3000],
        name: "Council on Environmental Quality and Office of Environmental Qua",
        id: "leaf-320",
        discretion: "discretionary",
      },
    ],
  },
  {
    value: [407000],
    name: "National Archives and Records Administration",
    id: "branch-27",
    discretion: null,
    children: [
      {
        value: [407000],
        name: "National Archives and Records Administration",
        id: "leaf-399",
        discretion: "discretionary",
      },
    ],
  },
  {
    value: [32000],
    name: "Recovery Accountability and Transparency Board",
    id: "branch-32",
    discretion: null,
    children: [
      {
        value: [32000],
        name: "Recovery Act Accountability and Transparency Board",
        id: "leaf-526",
        discretion: "discretionary",
      },
    ],
  },
  {
    value: [7000],
    name: "Access Board",
    id: "branch-0",
    discretion: null,
    children: [
      {
        value: [7000],
        name: "Architectural and Transportation Barriers Compliance Board",
        id: "leaf-1",
        discretion: "discretionary",
      },
    ],
  },
  {
    value: [6000],
    name: "Committee for Purchase from People Who Are Blind or Severely Dis",
    id: "branch-1",
    discretion: null,
    children: [
      {
        value: [6000],
        name: "Committee for Purchase from People who are Blind or Severely Dis",
        id: "leaf-2",
        discretion: "discretionary",
      },
    ],
  },
  {
    value: [2000],
    name: "Federal Financial Institutions Examination Council",
    id: "branch-22",
    discretion: null,
    children: [
      {
        value: [2000],
        name: "Federal Financial Institutions Examination Council Appraisal Sub",
        id: "leaf-341",
        discretion: "mandatory",
      },
    ],
  },
  {
    value: [0],
    name: "Securities and Exchange Commission",
    id: "branch-33",
    discretion: null,
  },
];
