import Head from "next/head";
import { HvButton, HvTypography } from "@hitachivantara/uikit-react-core";

import styles from "~/styles/Home.module.css";

export default function Home() {
  return (
    <>
      <Head>
        <title>UI Kit Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={styles.main}>
        <div>
          <HvTypography variant="title1">Hello from UI Kit 👋</HvTypography>
          <HvTypography>
            Get started by editing&nbsp;
            <code className={styles.code}>pages/index.tsx</code>
          </HvTypography>
          <br />
          <HvButton variant="secondarySubtle">Button</HvButton>
        </div>
      </main>
    </>
  );
}
