# Bash script action
name: Blackduck Scan
description: Scans the project, uploads the results to blackduck and checks for unreviewed components

inputs:
  server-url:
    description: The URL of the Blackduck server
    required: true
  key:
    description: The API Key to authenticate the Blackduck calls
    required: true
  packages:
    description: The project packages and paths to check
    required: true
  exceptions:
    description: The component exceptions to discard on the unreviewed components validation
    required: true
  version:
    description: The project version (e.g. branch name)
    required: true

runs:
  using: "docker"
  image: "Dockerfile"
  args:
    - ${{ inputs.server-url}}
    - ${{ inputs.key}}
    - ${{ inputs.packages}}
    - ${{ inputs.version}}
