export const componentsData = [
  { id: "avatar", label: "Avatar", href: "#avatar" },
  { id: "badge", label: "Badge", href: "#badge" },
  { id: "breadcrumb", label: "BreadCrumb", href: "#breadcrumb" },
  { id: "bulkactions", label: "Bulk Actions", href: "#bulkactions" },
  { id: "button", label: "Button", href: "#button" },
  { id: "calendar", label: "Calendar", href: "#calendar" },
  { id: "card", label: "Card", href: "#card" },
  { id: "checkbox", label: "Checkbox", href: "#checkbox" },
  { id: "dialog", label: "Dialog", href: "#dialog" },
  { id: "dotpagination", label: "Dot Pagination", href: "#dotpagination" },
  {
    id: "dropdownmenu",
    label: "DropDownMenu",
    href: "#dropdownmenu",
  },
  { id: "emptystate", label: "Empty State", href: "#emptystate" },
  { id: "fileuploader", label: "File Uploader", href: "#fileuploader" },
  { id: "icons", label: "Icons", href: "#icons" },
  { id: "input", label: "Input", href: "#input" },
  { id: "loading", label: "Loading", href: "#loading" },
  { id: "pagination", label: "Pagination", href: "#pagination" },
  { id: "progressbar", label: "Progress Bar", href: "#progressbar" },
  { id: "snackbar", label: "Snackbar", href: "#snackbar" },
  { id: "radio", label: "Radio", href: "#radio" },
  { id: "switch", label: "Switch", href: "#switch" },
  { id: "tags", label: "Tags", href: "#tags" },
  { id: "tagsinput", label: "Tags Input", href: "#tagsinput" },
  { id: "tooltip", label: "Tooltip", href: "#tooltip" },
  { id: "typography", label: "Typography", href: "#typography" },
  {
    id: "verticalnavigation",
    label: "Vertical Navigation",
    href: "#verticalnavigation",
  },
];
