import { createClasses } from "../utils/classes";

export const { staticClasses, useClasses } = createClasses("HvGrid", {
  root: {},
  container: {},
  item: {},
  zeroMinWidth: {},
  "direction-xs-column": {},
  "direction-xs-reverse": {},
  "direction-xs-row-reverse": {},
  "wrap-xs-nowrap": {},
  "wrap-xs-wrap-reverse": {},
  "spacing-xs-1": {},
  "spacing-xs-2": {},
  "spacing-xs-3": {},
  "spacing-xs-4": {},
  "spacing-xs-5": {},
  "spacing-xs-6": {},
  "spacing-xs-7": {},
  "spacing-xs-8": {},
  "spacing-xs-9": {},
  "spacing-xs-10": {},
  "grid-xs-auto": {},
  "grid-xs-true": {},
  "grid-xs-1": {},
  "grid-xs-2": {},
  "grid-xs-3": {},
  "grid-xs-4": {},
  "grid-xs-5": {},
  "grid-xs-6": {},
  "grid-xs-7": {},
  "grid-xs-8": {},
  "grid-xs-9": {},
  "grid-xs-10": {},
  "grid-xs-11": {},
  "grid-xs-12": {},
});
