*** Variables ***
${BROWSER}           chrome
${components}        ${STORYBOOK_URL}/iframe.html?id=components-
${forms}             ${STORYBOOK_URL}/iframe.html?id=forms-
${patterns}          ${STORYBOOK_URL}/iframe.html?id=patterns-
${STORYBOOK_URL}     http://localhost:9001
${tests}             ${STORYBOOK_URL}/iframe.html?id=tests-
${lab}               ${STORYBOOK_URL}/iframe.html?id=lab-
