#!/bin/sh
. "$(dirname "$0")/_/husky.sh"

PATH="/usr/local/bin:$PATH"

if [ -f $HOME/.nvm/nvm.sh ]
then
  . $HOME/.nvm/nvm.sh
  PATH="$HOME/.nvm/versions/node/$(nvm current)/bin:$PATH"
fi

npx --no-install commitlint --edit $1
