name: CI (master)
on:
  schedule:
    - cron: '0 5 * * *' # daily at 05:00
  pull_request:
    branches:
      - next

env:
  RESOLVE_REGISTRY: https://repo.orl.eng.hitachivantara.com/artifactory/api/npm/npm/


jobs:
  Build:
    runs-on: [self-hosted, Linux]
    container:
      image: node:12.14.1-buster
      options: -u 1000 # buildguy

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Install
        run: |
          npm config set @hv:registry ${RESOLVE_REGISTRY}
          npm ci

      - name: Bootstrap
        run: npm run bootstrap

      - name: Lint
        run: npm run lint

      - name: Test
        run: npm run test

      - name: Generate Storybook
        run: npm run automation:package

      - name: Archive Storybook
        uses: actions/upload-artifact@v1
        with:
          name: storybook
          path: automation/storybook/dist
          
  Robot_pa11y:
    needs: Build
    runs-on: [self-hosted, Windows]

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Install PA11Y
        working-directory: ./automation/robot
        shell: cmd
        run: npm ci

      - name: Fetch Storybook
        uses: actions/download-artifact@v1
        with:
          name: storybook
          path: .github/storybook/www

      - name: Run Storybook
        uses: ./.github/storybook

      - name: Run PA11Y
        shell: cmd
        run: >-
          robot
          --variable STORYBOOK_URL:http://localhost:9002
          --include pa11y
          --outputdir reports
          --report report.html
          --log log.html
          automation\robot\storybook\core

      - name: Save Reports
        uses: actions/upload-artifact@v1
        if: always()
        with:
          name: pa11y-reports
          path: reports

  Robot:
    needs: Build
    runs-on: [self-hosted, Windows]
    strategy:
      fail-fast: false
      matrix:
        browser: [firefox, ie, chrome]

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Fetch Storybook
        uses: actions/download-artifact@v1
        with:
          name: storybook
          path: .github/storybook/www

      - name: Run Storybook
        uses: ./.github/storybook

      - name: Run SELENIUM Robot
        shell: cmd
        run: |
          robot --variable STORYBOOK_URL:http://localhost:9002  --variable BROWSER:${{ matrix.browser }} --exclude classORbug-infrastructure-${{ matrix.browser }} --exclude pa11y --exclude issueORissue-${{ matrix.browser }}ORimage --exclude bug-${{ matrix.browser }}ORbug-${{ matrix.browser }}-webdriverORbug-jenkins --outputdir reports --output firstRun.xml --report NONE --log NONE automation\robot\storybook\core\table
          rebot --outputdir reports --output output.xml reports\firstRun.xml

      - name: ReRun SELENIUM Robot Failed
        if: failure()
        shell: cmd
        run: |
          robot --rerunfailed reports\firstRun.xml --variable STORYBOOK_URL:http://localhost:9002 --variable BROWSER:${{ matrix.browser }} --outputdir reports --output secondRun.xml --report NONE --log NONE automation\robot\storybook\core
          rebot --outputdir reports --output output.xml --merge reports\firstRun.xml reports\secondRun.xml

      - name: Save Reports
        uses: actions/upload-artifact@v1
        if: always()
        with:
          name: ${{ matrix.browser }}-reports
          path: reports

  Release:
    if: github.event_name == 'schedule'
    needs: Robot
    runs-on: [self-hosted, Linux]
    steps:
      - name: Trigger Release
        uses: actions/github-script@0.8.0
        env:
          RELEASE_COMMIT_MESSAGE: 'chore(release): publish'
        with:
          # repo scope token is required to generate a dispatch event
          github-token: ${{ secrets.BUILD_TOKEN }}
          script: |
            const branch = await github.repos.getBranch({
              owner: context.repo.owner,
              repo: context.repo.repo,
              branch: context.ref
            })
            
            const message = branch.data.commit.commit.message
            
            if(!message.includes('${{ env.RELEASE_COMMIT_MESSAGE }}')){
              console.log('Last commit not released, triggering a new release.')
              
              await github.repos.createDispatchEvent({
                owner: context.repo.owner,
                repo: context.repo.repo,
                event_type: 'release'
              })
            } else {
              console.log('Last commit already released.')
            }
