name: Checks

on:
  workflow_dispatch:
  workflow_call:
    inputs:
      a11y-publish:
        type: boolean
        default: false
        required: false
      a11y-exit:
        type: boolean
        default: false
        required: false

env:
  LICENSES_WHITELIST: Apache-2.0;ISC;BSD-2-Clause;BSD-3-Clause;MIT;W3C;Zlib;CC-BY-4.0;Hippocratic-2.1;Python-2.0;MPL-2.0;Unlicense;EPL-2.0;BSD;BlueOak-1.0.0;CC0-1.0;CC-BY-3.0;WTFPL

jobs:
  checks:
    name: Static Tests
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install Dependencies
        uses: ./.github/actions/install-dependencies

      - name: License Check
        run: |
          npx license-checker-rseidelsohn --onlyAllow "${{ env.LICENSES_WHITELIST }}" --excludePackagesStartingWith "@applitools;buffers;flatbuffers"

      - name: Security Audit
        run: npm audit --workspaces --omit dev

      - name: Run Format
        run: npm run prettier

      - name: Run Lint
        run: npm run lint

      - name: Run Typecheck
        run: npm run typecheck

  test:
    name: Unit Tests
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install Dependencies
        uses: ./.github/actions/install-dependencies

      - name: Run Test
        run: npm run test

  playwright:
    name: Playwright Tests
    uses: ./.github/workflows/tests-playwright.yml

  a11y:
    name: A11y Tests
    uses: ./.github/workflows/tests-a11y.yml
    secrets: inherit
    with:
      publish: ${{ inputs.a11y-publish }}
      exit: ${{ inputs.a11y-exit }}

  build:
    name: Build
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install Dependencies
        uses: ./.github/actions/install-dependencies

      - name: Run Build
        run: npm run build
