name: Visual Tests

on:
  workflow_dispatch:
  workflow_call:
    inputs:
      batch-id:
        type: string

jobs:
  chromatic:
    name: Chromatic
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          # Pulls all commits (needed for Chromatic)
          fetch-depth: 0

      - name: Install Dependencies
        uses: ./.github/actions/install-dependencies

      - name: Publish to Chromatic
        id: publish
        uses: chromaui/action@latest
        with:
          configFile: .config/chromatic.config.json
          projectToken: ${{ secrets.CHROMATIC_PROJECT_TOKEN }}
          forceRebuild: true

      # Add red mark to workflow if it failed
      - name: Evaluate Fail
        if: ${{ steps.publish.outcome == 'failure' || steps.publish.outputs.changeCount != '0' || steps.publish.outputs.errorCount != '0' }}
        run: exit 1
