name: Visual Tests

on:
  workflow_dispatch:
  workflow_call:
    inputs:
      batch-id:
        type: string

env:
  APPLITOOLS_API_KEY: ${{ secrets.APPLITOOLS_API_KEY }}
  APPLITOOLS_BATCH_ID: ${{ inputs.batch-id || github.ref_name }}
  APPLITOOLS_BRANCH_NAME: "lumada-design/hv-uikit-react/master"

jobs:
  chromatic:
    name: Chromatic
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          # Pulls all commits (needed for Chromatic)
          fetch-depth: 0

      - name: Install Dependencies
        uses: ./.github/actions/install-dependencies
        env:
          # Pulls all commits (needed for Chromatic)
          FETCH_DEPTH: 0

      - name: Publish to Chromatic
        id: publish
        uses: chromaui/action@latest
        with:
          configFile: .config/chromatic.config.json
          projectToken: ${{ secrets.CHROMATIC_PROJECT_TOKEN }}
          forceRebuild: true

      # Add red mark to workflow if it failed
      - name: Evaluate Fail
        if: ${{ steps.publish.outcome == 'failure' || steps.publish.outputs.changeCount != '0' || steps.publish.outputs.errorCount != '0' }}
        run: exit 1

  applitools:
    name: Applitools
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install Dependencies
        uses: ./.github/actions/install-dependencies

      - name: Set Applitools App Name
        id: set-app-name
        run: |
          if [[ "${{ github.ref_name }}" == "next"* ]]; then
            echo "APPLITOOLS_APP_NAME=NEXT UI Kit" >> $GITHUB_ENV
          else
          echo "APPLITOOLS_APP_NAME=UI Kit" >> $GITHUB_ENV
          fi

      - name: Eyes Storybook
        run: npm run test:eyes
        timeout-minutes: 30
