name: Applitools

on:
  workflow_dispatch:
  workflow_call:
    secrets:
      APPLITOOLS_API_KEY:
        required: true
    inputs:
      batch-id:
        type: string

env:
  APPLITOOLS_API_KEY: ${{ secrets.APPLITOOLS_API_KEY }}
  APPLITOOLS_BATCH_ID: ${{ inputs.batch-id || github.ref_name }}
  APPLITOOLS_BRANCH_NAME: "lumada-design/hv-uikit-react/master"

jobs:
  run-tests:
    name: Run Tests
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Install Dependencies
        uses: ./.github/actions/install-dependencies

      - name: Build Storybook
        run: npm run build:doc
        env:
          NODE_OPTIONS: "--max_old_space_size=8192"
        shell: bash

      - name: Set Applitools App Name
        id: set-app-name
        run: |
          if [[ "${{ github.ref_name }}" == "next"* ]]; then
            echo "APPLITOOLS_APP_NAME=NEXT UI Kit" >> $GITHUB_ENV
          else
          echo "APPLITOOLS_APP_NAME=UI Kit" >> $GITHUB_ENV
          fi

      - name: Eyes Storybook
        run: |
          npx concurrently -k -s first -n "SB,TEST" -c "magenta,blue" \
          "npx http-server dist --port 6006 --silent" \
          "npx wait-on tcp:6006 && npm run test:eyes -- -u http://localhost:6006" || true
        timeout-minutes: 30

      - name: Archive Logs
        uses: actions/upload-artifact@v3
        if: failure()
        with:
          name: applitools-logs
          path: ${{ github.workspace }}/applitools-logs.txt
          retention-days: 2
