name: Playwright Tests

on:
  workflow_dispatch:
  workflow_call:

jobs:
  tests:
    name: Run Tests
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        PROJECT: ["chrome", "firefox"]

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install Dependencies
        uses: ./.github/actions/install-dependencies

      - name: Install Playwright
        run: npx playwright install --with-deps

      - name: Run Playwright tests
        run: npx playwright test --project=${{ matrix.PROJECT }}

      - name: Archive Playwright report
        if: failure()
        uses: actions/upload-artifact@v4
        with:
          name: Playwright report-[${{ matrix.PROJECT }}]
          path: |
            playwright-report/
          retention-days: 5
