name: A11y Tests

on:
  workflow_dispatch:
  workflow_call:

jobs:
  run-tests:
    name: A11y Tests
    runs-on: ubuntu-latest
    continue-on-error: true

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install Dependencies
        uses: ./.github/actions/install-dependencies

      - name: Install Playwright
        run: npx playwright install --with-deps

      - name: Build Storybook
        run: npm run build:doc
        env:
          NODE_OPTIONS: "--max_old_space_size=8192"
        shell: bash

      - name: Run Tests
        run: |
          npx concurrently -k -s first -n "SB,TEST" -c "magenta,blue" \
          "npx serve dist -l 6006 -L" \
          "npx wait-on tcp:6006 && npm run test:a11y"
