name: Tests

on:
  workflow_dispatch:
  workflow_call:

env:
  LICENSES_WHITELIST: Apache-2.0;ISC;BSD-2-Clause;BSD-3-Clause;MIT;W3C;Zlib;CC-BY-4.0;Hippocratic-2.1;Python-2.0;MPL-2.0;Unlicense;EPL-2.0;BSD;BlueOak-1.0.0;CC0-1.0;CC-BY-3.0;WTFPL

jobs:
  checks:
    name: Static Checks
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install Dependencies
        uses: ./.github/actions/install-dependencies

      - name: License Check
        run: |
          npx license-checker-rseidelsohn --onlyAllow "${{ env.LICENSES_WHITELIST }}" --excludePackagesStartingWith "buffers;flatbuffers"

      - name: Security Audit
        run: npm audit --workspaces --omit dev

      - name: Run Format
        run: npm run prettier

      - name: Run Lint
        run: npm run lint

      - name: Run Typecheck
        run: npm run typecheck

  test:
    name: Unit Tests
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install Dependencies
        uses: ./.github/actions/install-dependencies

      - name: Run Test
        run: npm run test

  playwright:
    name: Playwright Tests
    runs-on: ubuntu-latest

    strategy:
      fail-fast: false
      matrix:
        PROJECT: ["chrome", "firefox"]

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install Dependencies
        uses: ./.github/actions/install-dependencies

      - name: Install Playwright
        run: npx playwright install --with-deps

      - name: Run Playwright tests
        run: npx playwright test --project=${{ matrix.PROJECT }}

      - name: Archive Playwright report
        if: failure()
        uses: actions/upload-artifact@v4
        with:
          name: report-[${{ matrix.PROJECT }}]
          path: playwright-report/
          retention-days: 5

  a11y:
    name: A11y Tests
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install Dependencies
        uses: ./.github/actions/install-dependencies

      - name: Install Playwright
        run: npx playwright install --with-deps

      - name: Build Storybook
        run: npm run build:doc:test
        env:
          NODE_OPTIONS: "--max_old_space_size=8192"

      - name: Run Tests
        run: |
          npx concurrently -k -s first -n "SB,TEST" -c "magenta,blue" \
          "npx serve dist -l 6006 -L" \
          "npx wait-on tcp:6006 && npm run test:a11y"

  build:
    name: Build
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install Dependencies
        uses: ./.github/actions/install-dependencies

      - name: Run Build
        run: npm run build
