name: Chromatic

on:
  workflow_dispatch:
  workflow_call:

jobs:
  run-tests:
    name: Run Tests
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          # Pulls all commits (needed for Chromatic)
          fetch-depth: 0

      - name: Install Dependencies
        uses: ./.github/actions/install-dependencies
        env:
          # Pulls all commits (needed for Chromatic)
          FETCH_DEPTH: 0

      - name: Publish to Chromatic
        uses: chromaui/action@latest
        with:
          configFile: .config/chromatic.config.json
          projectToken: ${{ secrets.CHROMATIC_PROJECT_TOKEN }}
