name: a11y

on:
  workflow_dispatch:
  workflow_call:
    secrets:
      ORG_GHPAGES_DEPLOY_KEY:
        required: true

jobs:
  run-tests:
    name: Run Tests
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Install Dependencies
        uses: ./.github/actions/install-dependencies

      - name: Build Storybook
        run: npm run build:doc
        env:
          NODE_OPTIONS: "--max_old_space_size=8192"
        shell: bash

      - name: Run Tests
        run: |
          npx concurrently -k -s first -n "SB,TEST" -c "magenta,blue" \
          "npx serve dist -l 6006 -L" \
          "npx wait-on tcp:6006 && npm run test:a11y" || true

      - name: Archive a11y report
        if: always()
        uses: actions/upload-artifact@v3
        with:
          name: a11y-report
          path: ${{ github.workspace }}/a11y-report
          retention-days: 2

      - name: Deploy Artifacts
        if: always()
        uses: ./.github/actions/deploy-artifacts
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          ORG_GHPAGES_DEPLOY_KEY: ${{ secrets.ORG_GHPAGES_DEPLOY_KEY }}
          PUBLISH_REPO: ${{ github.repository_owner }}/${{ github.repository_owner }}.github.io
          PUBLISH_FOLDER: uikit-a11y
          PUBLISH_MESSAGE: "chore: publish NEXT UI Kit accessibility report"
          URL: https://${{ github.repository_owner }}.github.io/uikit-a11y/
          ARTIFACT: a11y-report
